spring:
  application:
    name: vehicle-sensor-api

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:postgresql://localhost:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

mqtt:
  broker: ${MQTT_HOST}
  username: ${MQTT_USER}
  password: ${MQTT_PASSWORD}
  client-id: vehicle-sensor-api
  topic: lab/+/veiculos
